"""Initial migration

Revision ID: 6786ab019ec9
Revises: 8a09088aa464
Create Date: 2025-03-08 17:19:32.348767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6786ab019ec9'
down_revision = '8a09088aa464'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
